### ISSUE TITLE
Fix gitlab link :)

### ISSUE THREAD

**Issue by adhamfarrag** [cameronbaney/portfolio-2020#4]
I was checking your website and you led me to using Cascadia Code font, very grateful for that. That's why I felt I need to give back and point out that your gitlab link is broken. Thanks again.

**Comment by cameronbaney** [comment]
@adhamfarrag Thank you very much! I'm glad that my portfolio was able to help you. Hope you're enjoying the font, I keep coming back to it after checking out other fonts.

**Comment by cameronbaney** [comment]
Fixed with c12b411
